### ISSUE TITLE
response Transfer-Encoding: chunked error

### ISSUE THREAD

**Issue by LuPan2015** [renatoathaydes/rawhttp#9] opened 2019-05-10 03:11 UTC
error info
`java.lang.IllegalStateException: Invalid chunk-size (too big, more than 4 hex-digits)
	at rawhttp.core.body.ChunkedBodyParser.readChunkSize(ChunkedBodyParser.java:215)
	at rawhttp.core.body.ChunkedBodyParser.parseChunkedBody(ChunkedBodyParser.java:97)
	at rawhttp.core.body.BodyConsumer$ChunkedBodyConsumer.consumeInto(BodyConsumer.java:93)
null
	at rawhttp.core.body.BodyConsumer.consume(BodyConsumer.java:29)
	at rawhttp.core.body.EagerBodyReader.<init>(EagerBodyReader.java:35)
	at rawhttp.core.body.LazyBodyReader.eager(LazyBodyReader.java:68)
	at rawhttp.core.EagerHttpResponse.from(EagerHttpResponse.java:52)
	at rawhttp.core.RawHttpResponse.eagerly(RawHttpResponse.java:95)
	at rawhttp.core.RawHttpResponse.eagerly(RawHttpResponse.java:79)`

**Comment by renatoathaydes** [comment] 2019-05-10 05:22
Where did you get this error from?
Please provide information. I can't fix things by looking at an error stacktrace only.

**Comment by WangGaofei** [comment] 2019-05-10 08:07
We are trying to parse google http response with chunk and gzip encoding, but what we get is
java.lang.IllegalStateException: Invalid chunk-size (too big, more than 4 hex-digits)
	at rawhttp.core.body.ChunkedBodyParser.readChunkSize(ChunkedBodyParser.java:215)
	at rawhttp.core.body.ChunkedBodyParser.parseChunkedBody(ChunkedBodyParser.java:97)
	at rawhttp.core.body.BodyConsumer$ChunkedBodyConsumer.consumeInto(BodyConsumer.java:93)
	at rawhttp.core.body.BodyConsumer.consume(BodyConsumer.java:29)
	at rawhttp.core.body.EagerBodyReader.<init>(EagerBodyReader.java:35)
	at rawhttp.core.body.LazyBodyReader.eager(LazyBodyReader.java:68)
	at rawhttp.core.EagerHttpResponse.from(EagerHttpResponse.java:52)
	at rawhttp.core.RawHttpResponse.eagerly(RawHttpResponse.java:95)
	at rawhttp.core.RawHttpResponse.eagerly(RawHttpResponse.java:79)
	at com.bfd.engine.ParserEngine.extract(ParserEngine.java:197)
	at com.bfd.util.SazUtil.main(SazUtil.java:69)
*********************************************************************************************raw/706_s.txt**********************************************************************************************
java.lang.IllegalStateException: Invalid chunk-size (too big, more than 4 hex-digits)
	at rawhttp.core.body.ChunkedBodyParser.readChunkSize(ChunkedBodyParser.java:215)
	at rawhttp.core.body.ChunkedBodyParser.parseChunkedBody(ChunkedBodyParser.java:97)
	at rawhttp.core.body.BodyConsumer$ChunkedBodyConsumer.consumeInto(BodyConsumer.java:93)
	at rawhttp.core.body.BodyConsumer.consume(BodyConsumer.java:29)
	at rawhttp.core.body.EagerBodyReader.<init>(EagerBodyReader.java:35)
	at rawhttp.core.body.LazyBodyReader.eager(LazyBodyReader.java:68)
	at rawhttp.core.EagerHttpResponse.from(EagerHttpResponse.java:52)
	at rawhttp.core.RawHttpResponse.eagerly(RawHttpResponse.java:95)
	at rawhttp.core.RawHttpResponse.eagerly(RawHttpResponse.java:79)
	at com.bfd.engine.ParserEngine.extract(ParserEngine.java:197)
	at com.bfd.util.SazUtil.main(SazUtil.java:69)

Please check the attachements below.

[144_c.txt](https://github.com/renatoathaydes/rawhttp/files/3165476/144_c.txt)
[144_s.txt](https://github.com/renatoathaydes/rawhttp/files/3165477/144_s.txt)

![image](https://user-images.githubusercontent.com/16849581/57512115-62d77f00-733d-11e9-9dc1-35eb1948e7e1.png)

**Comment by WangGaofei** [comment] 2019-05-10 08:18
We are using the latest version of RawHttp. It seems a perfect http library we love. 
The issue is similar to https://github.com/actix/actix-web/issues/674. But it is said that the issue in actix-web project is fixed.
		<dependency>
			<groupId>org.apache.httpcomponents</groupId>
			<artifactId>httpclient</artifactId>
			<version>4.5.7</version>
		</dependency>
		<dependency>
			<groupId>com.athaydes.rawhttp</groupId>
			<artifactId>rawhttp-core</artifactId>
			<version>2.1</version>
		</dependency>
		<dependency>
			<groupId>com.athaydes.rawhttp</groupId>
			<artifactId>rawhttp-cli</artifactId>
			<version>1.1.1</version>
			<type>zip</type>
		</dependency>

**Comment by renatoathaydes** [comment] 2019-05-10 08:35
Ok... This is indeed a strange chunk Google is sending... my interpretation of the spec, though, seems to have been incorrect now that I look into it more carefully.

RawHTTP does not allow chunk-sizes bigger than FFFF (65535 bytes), so it expects at most 4 hexa-decimal characters for `chunk-size`.
However, the spec does not actually mention this and Google's message seems to be valid!

I will change the code as soon as possible to fix this... It's an easy fix, so if you have urgency, you could probably do it yourselves for now.

**Comment by WangGaofei** [comment] 2019-05-10 08:45
We are trying to solve the issue but in vain. Now we have no idea. I guess Google uses async request, and 0000001 means Async Not Ready.

**Comment by renatoathaydes** [comment] 2019-05-10 09:17
@WangGaofei fork this project, change this method to stop reading the chunk-size when it finds either a new line or `;`: https://github.com/renatoathaydes/rawhttp/blob/master/rawhttp-core/src/main/java/rawhttp/core/body/ChunkedBodyParser.java#L172

Can you do that?

**Comment by WangGaofei** [comment] 2019-05-10 10:21
I am not sure what does 00000001 and 0001 and 1 and 9 mean in the file. Or we can skip the section.
I know why this exception raised. But I don't understand the chunk format that Google generated.
As a result, I can modify the code like that, but not guarantee that data is correct.

**Comment by renatoathaydes** [comment] 2019-05-10 12:09
What you want to do is parse the hex String up to either new-line or `;` as a Hexadecimal number.

So, `00000001` means `1` in decimal. Something like `000000FF` would be 255, and so on... In Java this just means: `Integer.parseInt(hexaString, 16);`.

**Comment by renatoathaydes** [comment] 2019-05-10 19:54
I've fixed the issue in the `dev` branch. Would appreciate if you could test if it works for you now, before I release the change @WangGaofei  @LuPan2015 .

**Comment by WangGaofei** [comment] 2019-05-10 21:02
GOOD JOB. You are very nice and efficient. I need to go to Tianjin this morning. After that I will have a test. Thank you.

**Comment by renatoathaydes** [comment] 2019-05-10 21:04
No problem! Happy to help. Have a good trip :)

**Comment by WangGaofei** [comment] 2019-05-10 21:33
Info update: File 144_c.txt is request, file 144_s.txt is response. Join 2 files with /r/n, then pass it into RawHttp. These files are generated in .saz format using fiddler.

**Comment by LuPan2015** [comment] 2019-05-11 02:50
@renatoathaydes Thanks, I have gained the dev branch the latest code and run successfully.But I get the response of the body data is garbled.
My test code is as follows:
`     

        String requestTxt = "src/main/resources/chunck/144_c.txt";
        String responseTxt = "/src/main/resources/chunck/144_s.txt";

        InputStream requestIn = new FileInputStream(new File(requestTxt));
        InputStream responseIn = new FileInputStream(new File(responseTxt));

        ByteArrayOutputStream bos = new ByteArrayOutputStream();
        byte data[] = new byte[4096];

        int count;
        while ((count = requestIn.read(data, 0, data.length)) != -1) {
            bos.write(data, 0, count);
        }
        bos.write("\r\n".getBytes("UTF-8"));

        while ((count = responseIn.read(data, 0, data.length)) != -1) {
            bos.write(data, 0, count);
        }

        RawHttpRequest request = null;
        RawHttpResponse response = null;
        RawHttp rawHttp = new RawHttp();
        ByteArrayInputStream bis = new ByteArrayInputStream(bos.toByteArray());
        request = rawHttp.parseRequest(bis).eagerly();
        response = rawHttp.parseResponse(bis).eagerly();
        System.out.println(response.getBody().toString());`

Get the reponse of body data is as follows:
![image](https://user-images.githubusercontent.com/10804128/57564179-3faedd00-73da-11e9-9e7a-67a611e4c990.png)

I don't know what reason is this。

**Comment by renatoathaydes** [comment] 2019-05-11 07:56
Can you try `String textBody = response.getBody().get().decodeBodyToString(UTF_8);` and print that? If the body is gzipped, then you need to decode it.

**Comment by LuPan2015** [comment] 2019-05-11 09:16
@renatoathaydes  
OK, I try to use the decodeBodyToString method.Seems still gibberish.My code is as follows:
`
    String requestTxt = "/src/main/resources/chunck/144_c.txt";
    String responseTxt = "/src/main/resources/chunck/144_s.txt";

    InputStream requestIn = new FileInputStream(new File(requestTxt));
    InputStream responseIn = new FileInputStream(new File(responseTxt));

    ByteArrayOutputStream bos = new ByteArrayOutputStream();
    byte data[] = new byte[4096];

    int count;
    while ((count = requestIn.read(data, 0, data.length)) != -1) {
        bos.write(data, 0, count);
    }
    bos.write("\r\n".getBytes("UTF-8"));

    while ((count = responseIn.read(data, 0, data.length)) != -1) {
        bos.write(data, 0, count);
    }

    RawHttpRequest request = null;
    RawHttpResponse response = null;
    RawHttp rawHttp = new RawHttp();
    ByteArrayInputStream bis = new ByteArrayInputStream(bos.toByteArray());
    request = rawHttp.parseRequest(bis).eagerly();
    response = rawHttp.parseResponse(bis).eagerly();
    System.out.println(response.getBody().get()
                .decodeBodyToString(Charset.forName("UTF-8")));
`
The results are as follows:
![image](https://user-images.githubusercontent.com/10804128/57567745-6e47aa80-7410-11e9-9634-3dff4e2f474b.png)

**Comment by renatoathaydes** [comment] 2019-05-11 10:48
Can you send me the response body you're having trouble with? Also the response headers so I know the encoding used.

**Comment by LuPan2015** [comment] 2019-05-11 11:56
Ok. The request header data is in the file 144_c.txt <https://github.com/renatoathaydes/rawhttp/files/3165476/144_c.txt>, and the request body data is in the file 144_s.txt <https://github.com/renatoathaydes/rawhttp/files/3165477/144_s.txt>.
You can directly run the following test code to see the results;

`
String requestTxt = "/src/main/resources/chunck/144_c.txt";
String responseTxt = "/src/main/resources/chunck/144_s.txt";
InputStream requestIn = new FileInputStream(new File(requestTxt));
InputStream responseIn = new FileInputStream(new File(responseTxt));

ByteArrayOutputStream bos = new ByteArrayOutputStream();
byte data[] = new byte[4096];

int count;
while ((count = requestIn.read(data, 0, data.length)) != -1) {
    bos.write(data, 0, count);
}
bos.write("\r\n".getBytes("UTF-8"));

while ((count = responseIn.read(data, 0, data.length)) != -1) {
    bos.write(data, 0, count);
}

RawHttpRequest request = null;
RawHttpResponse response = null;
RawHttp rawHttp = new RawHttp();
ByteArrayInputStream bis = new ByteArrayInputStream(bos.toByteArray());
request = rawHttp.parseRequest(bis).eagerly();
response = rawHttp.parseResponse(bis).eagerly();
System.out.println(response.getBody().get()
            .decodeBodyToString(Charset.forName("UTF-8")));
`

thanks!

**Comment by renatoathaydes** [comment] 2019-05-11 20:30
Ok, I found the problem.

The response uses the following relevant headers:

```
Transfer-Encoding: chunked
Content-Encoding: gzip
```

RawHTTP cares only about the transfer encoding because that's within the realm of transferring the HTTP message - which RawHTTP is responsible for doing. The [`Content-Encoding`](https://tools.ietf.org/html/rfc7231#section-3.1.2.2) is not used because that's an encoding addressed to the receiver of the message instead.

The spec says, further: _ Typically, the representation is only decoded just prior to rendering
   or analogous usage._

So, I believe the behaviour RawHTTP is presenting is correct in not unzipping the message body... however, that's not very helpful, I agree... so I think the best solution to this problem is to make the `decodeBodyToString` and `decodeBody` methods actually decode according to both the `Transfer-Encoding` and `Content-Encoding` headers... and add new methods for maintaining the representation encoding but not the transfer encoding, perhaps `unframeBodyToString` and `unframeBody` because the transfer-encoding can be seen, I believe, as part of framing the body.

**Comment by LuPan2015** [comment] 2019-05-11 22:58
Thank you gave me answer over the weekend.This problem I also don't know how to deal with, can you give me a solution for the sample code? 
thank you

**Comment by LuPan2015** [comment] 2019-05-12 10:41
@renatoathaydes 
The problem solved.After I get the response body, one by one the chunck of decompression.But I think the best solution is realized in decodeBodyToString method is better.What time is convenient for you of the dev branch and publish to the maven repository?Thank you, have a nice weekend.

**Comment by renatoathaydes** [comment] 2019-05-12 18:22
You can get your data for now by decompressing the body:

```java
byte[] body = response.getBody().get().decodeBody();

java.io.ByteArrayInputStream bytein = new java.io.ByteArrayInputStream(body);
java.util.zip.GZIPInputStream gzin = new java.util.zip.GZIPInputStream(bytein);
java.io.ByteArrayOutputStream byteout = new java.io.ByteArrayOutputStream();

int res = 0;
byte buf[] = new byte[1024];
while (res >= 0) {
    res = gzin.read(buf, 0, buf.length);
    if (res > 0) {
        byteout.write(buf, 0, res);
    }
}
byte[] uncompressed = byteout.toByteArray();

System.out.println(new String(uncompressed, StandardCharsets.UTF_8));
```

**Comment by LuPan2015** [comment] 2019-05-13 01:23
@renatoathaydes  Because the data is according to block transmission, and it cannot be directly extract.
My test code is:
```
byte[] bytes = response.getBody().get().asRawBytes();
String data =uncompress(bytes,true,"UTF-8");
public static String uncompress(byte[] str,boolean isChunk,String outEncode)throws Exception{
        if (isChunk){
            StringBuilder sb = new StringBuilder(); //解压后的数据

            int chunkSize = 0;
            boolean start = false; //是否开始读取数据
            byte[] data = null; //实际数据
            int index = 0; //偏移量
            StringBuilder tmpChunckSize = new StringBuilder("0");

            int t = 0;

            //chunk方式需要一步步的解压缩才行
            for (int i=0;i <= str.length;i++){
                if (start){ //还在读写范围内
                    if ( index <chunkSize){
                        data[index++] = str[i];
                    }else {
                        //数据长度达到
                        start = false;
                        String chunckData  = uncompress(data,"UTF-8");
                        data = null;
                        chunkSize = 0;
                        sb.append(chunckData);
                        index = 0;
                    }
                }else {
                    if (str[i] == 10 && t == 13){ //\r\n
                        System.out.println(tmpChunckSize.toString());
                        chunkSize = Integer.valueOf(tmpChunckSize.toString(),16);
                        data = new byte[chunkSize];
                        tmpChunckSize = new StringBuilder("0"); //清空长度
                        if (chunkSize > 0){
                            start = true;
                        }
                    }else {
                        if (str[i] !=13 && str[i] >= 48 && str[i] <= 122){ //排除\r
                            tmpChunckSize.append((char) str[i]);
                        }
                        if (t == 10 && str[i] == 48){ //如果为0
                            break;
                        }
                    }
                }

                t = str[i];

            }
            return sb.toString();
        }else {
            return  uncompress(str,outEncode);
        }

    }
```
Have passed this test scheme。

**Comment by renatoathaydes** [comment] 2019-05-13 07:16
The code I posted works... you're doing too much in your code that is not necessary.

**Comment by WangGaofei** [comment] 2019-05-13 12:44
@renatoathaydes Thank you for your help. Your library is perfect and flexible. And we have made huge progress based on your library. We change the code a bit, it works like a charmer.

Please look at the changes. It will unchunk and decompress the data automatically. You can perform a new release, I think.

![image](https://user-images.githubusercontent.com/16849581/57621942-329f1300-75bf-11e9-9a6c-4db963f77919.png)

rawhttp.core.RawHttp

    public FramedBody getFramedBody(StartLine startLine, RawHttpHeaders headers) {
    	List<String> encodings = new ArrayList<String>();
    	List<String> contentEncoding = headers.get("Content-Encoding", ",\\s*");
        List<String> transferEncodings = headers.get("Transfer-Encoding", ",\\s*");
        encodings.addAll(contentEncoding);
        encodings.addAll(transferEncodings);
        BodyDecoder bodyDecoder = new BodyDecoder(options.getEncodingRegistry(), encodings);

        boolean isChunked = !transferEncodings.isEmpty() &&
                transferEncodings.get(transferEncodings.size() - 1).equalsIgnoreCase("chunked");

        if (isChunked) {
            return new FramedBody.Chunked(bodyDecoder, metadataParser);
        }
        List<String> lengthValues = headers.get("Content-Length");
        if (lengthValues.isEmpty()) {
            if (startLine instanceof StatusLine) {
                // response has no message framing information available
                return new FramedBody.CloseTerminated(bodyDecoder);
            }
            // request body without framing is not allowed
            throw new InvalidMessageFrame("The length of the request body cannot be determined. " +
                    "The Content-Length header is missing and the Transfer-Encoding header does not " +
                    "indicate the message is chunked");
        }
        if (lengthValues.size() > 1) {
            throw new InvalidMessageFrame("More than one Content-Length header value is present");
        }
        long bodyLength;
        try {
            bodyLength = Long.parseLong(lengthValues.get(0));
        } catch (NumberFormatException e) {
            throw new InvalidMessageFrame("Content-Length header value is not a valid number");
        }
        return new FramedBody.ContentLength(bodyDecoder, bodyLength);
    }

**Closed** 2019-05-16 19:29 UTC
Labels: bug, fixed-waiting-for-release, good first issue

**Comment by renatoathaydes** [comment] 2019-05-16 19:32
@LuPan2015 it's released now!
